package org.perfectsmiles.system.model.enums;

public enum Permission {
    MANAGE_USERS,
    CREATE_USERS,
    EDIT_USERS,
    DISABLE_USERS,
    VIEW_PATIENTS,
    CREATE_PATIENTS,
    EDIT_PATIENTS,
    DISABLE_PATIENTS,
    VIEW_TREATMENTS,
    CREATE_TREATMENTS,
    EDIT_TREATMENTS,
    DISABLE_TREATMENTS,
    VIEW_BUDGETS,
    CREATE_BUDGETS,
    EDIT_BUDGETS,
    DELETE_BUDGETS,
    APPROVE_BUDGETS,
    MANAGE_ROLES,
    MANAGE_PERMISSIONS
}